# Disable bors on the bors temp branch
branches:
  except:
    - staging.tmp
    - trying.tmp

language: rust
rust:
  - nightly-2020-04-06

os:
  - linux

cache: cargo

install:
  - make -j8 setup

script:
  - make test
